version: "3.9"

services:
  redis:
    image: redis:7
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  test:
    image: node:20
    working_dir: /workspace
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - ./:/workspace
    command: bash -lc "npm ci && npm run build && npm test"
