site_name: Node Quartz
site_description: Distributed, Resilient, Redis‑Backed Job Scheduler for Node.js
site_url: https://xjodoin.github.io/node-quartz/
repo_url: https://github.com/xjodoin/node-quartz
repo_name: xjodoin/node-quartz
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.action.edit
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage: usage.md
  - CLI: cli.md
  - Job Store: store.md
  - Architecture: architecture.md
  - API: api.md
  - LLMs: llms.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xjodoin/node-quartz
